export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_DONE = 'GET_PRODUCT_LIST_DONE';

export const CREATE_SEARCH_ADS_BY_SUGGEST = 'CREATE_SEARCH_ADS_BY_SUGGEST';
export const CREATE_SEARCH_ADS_BY_SUGGEST_DONE = 'CREATE_SEARCH_ADS_BY_SUGGEST_DONE';
