const ADS_DETAIL = 'ADS_DETAIL';

export const GET_ADS_DETAIL = 'GET_ADS_DETAIL';
export const GET_ADS_DETAIL_DONE = 'GET_ADS_DETAIL_DONE';

export const GET_CAMPAIGN_REPORT = 'GET_CAMPAIGN_REPORT';
export const GET_CAMPAIGN_REPORT_DONE = 'GET_CAMPAIGN_REPORT_DONE';

export const GET_CAMPAIGN_REPORT_COMPARE = 'GET_CAMPAIGN_REPORT_COMPARE';
export const GET_CAMPAIGN_REPORT_COMPARE_DONE =
  'GET_CAMPAIGN_REPORT_COMPARE_DONE';

export const REMOVE_CAMPAIGN_REPORT_COMPARE = 'REMOVE_CAMPAIGN_REPORT_COMPARE';

export const UPDATE_KEYWORD_STATE = 'UPDATE_KEYWORD_STATE';
export const UPDATE_KEYWORD_STATE_DONE = 'UPDATE_KEYWORD_STATE_DONE';

export const ADD_KEYWORD_ADS = 'ADD_KEYWORD_ADS';
export const ADD_KEYWORD_ADS_DONE = 'ADD_KEYWORD_ADS_DONE';

export const UPDATE_ADS_PREMIUM_RATE = 'UPDATE_ADS_PREMIUM_RATE';
export const UPDATE_ADS_PREMIUM_RATE_DONE = 'UPDATE_ADS_PREMIUM_RATE_DONE';

export const UPDATE_ADS_BASE_PRICE = 'UPDATE_ADS_BASE_PRICE';
export const UPDATE_ADS_BASE_PRICE_DONE = 'UPDATE_ADS_BASE_PRICE_DONE';

export const SHOW_MODAL_UPDATE_PREMIUM_RATE =
  ADS_DETAIL + 'SHOW_MODAL_UPDATE_PREMIUM_RATE';
export const HIDE_MODAL_UPDATE_PREMIUM_RATE =
  ADS_DETAIL + 'HIDE_MODAL_UPDATE_PREMIUM_RATE';
