export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
export const SEARCH_KEYWORD_DONE = 'SEARCH_KEYWORD_DONE';

export const GET_KEYWORD_FILES = 'GET_KEYWORD_FILES';
export const GET_KEYWORD_FILES_DONE = 'GET_KEYWORD_FILES_DONE';

export const GET_KEYWORD_FILE_DETAIL = 'GET_KEYWORD_FILE_DETAIL';
export const GET_KEYWORD_FILE_DETAIL_DONE = 'GET_KEYWORD_FILE_DETAIL_DONE';

export const CREATE_KEYWORD_FILE = 'CREATE_KEYWORD_FILE';
export const CREATE_KEYWORD_FILE_DONE = 'CREATE_KEYWORD_FILE_DONE';