export const GET_ADS_REPORT = 'GET_ADS_REPORT';
export const GET_ADS_REPORT_DONE = 'GET_ADS_REPORT_DONE';

export const KHAMPHA_GET_PRODUCT_ADS_LIST = 'KHAMPHA_GET_PRODUCT_ADS_LIST';
export const KHAMPHA_GET_PRODUCT_ADS_LIST_DONE =
  'KHAMPHA_GET_PRODUCT_ADS_LIST_DONE';

export const UPDATE_ADS_STATE = 'KHAMPHA_UPDATE_ADS_STATE';
export const UPDATE_ADS_STATE_DONE = 'KHAMPHA_UPDATE_ADS_STATE_DONE';

export const UPDATE_ADS_PLACEMENT = 'UPDATE_ADS_PLACEMENT';
export const UPDATE_ADS_PLACEMENT_DONE = 'UPDATE_ADS_PLACEMENT_DONE';
