export const GET_SHOP_LIST = 'GET_SHOP_LIST';
export const GET_SHOP_LIST_DONE = 'GET_SHOP_LIST_DONE';

export const GET_ADS_ACCOUNT_LIST = 'GET_ADS_ACCOUNT_LIST';
export const GET_ADS_ACCOUNT_LIST_DONE = 'GET_ADS_ACCOUNT_LIST_DONE';

export const GET_SHOP_REPORT_HOME = 'GET_SHOP_REPORT_HOME';
export const GET_SHOP_REPORT_HOME_DONE = 'GET_SHOP_REPORT_HOME_DONE';

export const GET_ADS_REPORT_HOME = 'GET_ADS_REPORT_HOME';
export const GET_ADS_REPORT_HOME_DONE = 'GET_ADS_REPORT_HOME_DONE';

export const GET_ADS_PERFORMANCE = 'GET_ADS_PERFORMANCE';
export const GET_ADS_PERFORMANCE_DONE = 'GET_ADS_PERFORMANCE_DONE';

export const SHOW_MODAL_SELECT_SHOP = 'SHOW_MODAL_SELECT_SHOP';
export const HIDE_MODAL_SELECT_SHOP = 'HIDE_MODAL_SELECT_SHOP';

export const SET_SHOP = 'SET_SHOP';
export const SET_ADS_ACCOUNT = 'SET_ADS_ACCOUNT';

export const GET_GOI_SANPHAM = 'GET_GOI_SANPHAM';
export const GET_GOI_SANPHAM_DONE = 'GET_GOI_SANPHAM_DONE';

export const SHOW_MODAL_SELECT_ADS_ACCOUNT = 'SHOW_MODAL_SELECT_ADS_ACCOUNT';
export const HIDE_MODAL_SELECT_ADS_ACCOUNT = 'HIDE_MODAL_SELECT_ADS_ACCOUNT';

export const GET_REPORT = 'GET_REPORT';
export const GET_REPORT_DONE = 'GET_REPORT_DONE';
