export const GET_ADS_REPORT = "GET_ADS_REPORT";
export const GET_ADS_REPORT_DONE = "GET_ADS_REPORT_DONE";

export const BAOCAO_GET_PRODUCT_ADS_LIST = "BAOCAO_GET_PRODUCT_ADS_LIST";
export const BAOCAO_GET_PRODUCT_ADS_LIST_DONE = "BAOCAO_GET_PRODUCT_ADS_LIST_DONE";

export const UPDATE_ADS_STATE = "UPDATE_ADS_STATE";
export const UPDATE_ADS_STATE_DONE = "UPDATE_ADS_STATE_DONE";