export const GET_SHOP_REPORT = "GET_SHOP_REPORT";
export const GET_SHOP_REPORT_DONE = "GET_SHOP_REPORT_DONE";

export const GET_SHOP_REPORT_COMPARE = "GET_SHOP_REPORT_COMPARE";
export const GET_SHOP_REPORT_COMPARE_DONE = "GET_SHOP_REPORT_COMPARE_DONE";

export const REMOVE_SHOP_REPORT_COMPARE = "REMOVE_SHOP_REPORT_COMPARE";

export const GET_PRODUCT_ADS_LIST = "GET_PRODUCT_ADS_LIST";
export const GET_PRODUCT_ADS_LIST_DONE = "GET_PRODUCT_ADS_LIST_DONE";
